/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface SButton {
    'color': 'primary' | 'primary-outline' | 'secondary' | 'light' | 'danger' | 'warn';
    'disabled': boolean;
    'shape': 'square' | 'round';
    'size': 'sx' | 'sm' | 'md' | 'lg' | 'xl';
    'type': 'button' | 'reset' | 'submit';
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLSButtonElement extends Components.SButton, HTMLStencilElement {}
  var HTMLSButtonElement: {
    prototype: HTMLSButtonElement;
    new (): HTMLSButtonElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    's-button': HTMLSButtonElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface SButton {
    'color'?: 'primary' | 'primary-outline' | 'secondary' | 'light' | 'danger' | 'warn';
    'disabled'?: boolean;
    'shape'?: 'square' | 'round';
    'size'?: 'sx' | 'sm' | 'md' | 'lg' | 'xl';
    'type'?: 'button' | 'reset' | 'submit';
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    's-button': SButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      's-button': LocalJSX.SButton & JSXBase.HTMLAttributes<HTMLSButtonElement>;
    }
  }
}


